### DISCUSSION TITLE
Add the ability to navigate cache to cache references from other records

### DISCUSSION THREAD

**Discussion by jerelmiller** [apollographql/apollo-client-devtools#954] [General]
The "Cache" tab in dev tools is a super useful way to peer into what the cache stores. The cache displays references to other records, but it would be super useful to be able to navigate to those other cache records by clicking on the ref.

Take the [example](https://www.apollographql.com/docs/react/caching/overview#visualizing-the-cache) on the [cache docs page](https://www.apollographql.com/docs/react/caching/overview). The tab displays the following data:

```
Person:cGVvcGxl0jE=
  id: cGVvcGxl0jE=
  __typename: Person
  name: Luke Skywalker
  homeworld:
    __ref: Planet:cGxhbmV0czox
```

It would be super useful to be able to click on `__ref` and have it open up the cache entry for `Planet:cGxhbmV0czox`.
